drop table member;
create table member (
id bigint generated by default as identity,
email varchar(255) not null,
age integer,
name varchar(255),
created_at datetime,
updated_at datetime,
primary key(id)
);